import { SeniorityLevel, SpokenLanguage } from '@/types';

export interface FallbackTemplate {
  id: string;
  titleTemplate: (role: string) => string;
  company: string;
  city: string;
  isRemote: boolean;
  workplaceType: string;
  seniority: SeniorityLevel;
  requiredSkills: string[];
  spokenLanguages?: SpokenLanguage[];
  salaryRange: { min: number; max: number; currency: string };
  slug: string;
  description: string;
}

export const FALLBACK_JOB_POOL: FallbackTemplate[] = [
  {
    id: '1',
    titleTemplate: (role) => `Senior ${role} (React / Next.js)`,
    company: 'CloudScale Solutions',
    city: 'Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'senior',
    requiredSkills: ['TypeScript', 'React', 'Next.js', 'Node.js', 'PostgreSQL'],
    spokenLanguages: [{ language: 'English', level: 'B2' }],
    salaryRange: { min: 20000, max: 26000, currency: 'PLN' },
    slug: 'demo-senior-react-developer',
    description: 'Lead frontend architecture and full-stack feature delivery on Next.js and Supabase/PostgreSQL.',
  },
  {
    id: '2',
    titleTemplate: () => 'Mid Full Stack Engineer',
    company: 'NextGen Fintech',
    city: 'Warsaw / Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'mid',
    requiredSkills: ['TypeScript', 'React', 'Node.js', 'Docker', 'AWS'],
    spokenLanguages: [
      { language: 'English', level: 'C1' },
      { language: 'Polish', level: 'B2' },
    ],
    salaryRange: { min: 16000, max: 22000, currency: 'PLN' },
    slug: 'demo-mid-fullstack-engineer',
    description: 'Join our product squad developing real-time financial dashboards. Requires React, TypeScript, and Node.js with AWS cloud deployments.',
  },
  {
    id: '3',
    titleTemplate: () => 'Frontend Specialist',
    company: 'Apex Digital Studio',
    city: 'Krakow',
    isRemote: false,
    workplaceType: 'office',
    seniority: 'mid',
    requiredSkills: ['JavaScript', 'React', 'CSS', 'HTML', 'Figma'],
    salaryRange: { min: 14000, max: 18000, currency: 'PLN' },
    slug: 'demo-frontend-specialist',
    description: 'Design and build high-performance user interfaces for international clients with rich CSS animations and React.',
  },
  {
    id: '4',
    titleTemplate: () => 'Lead Software Architect',
    company: 'Horizon Tech',
    city: 'Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'lead',
    requiredSkills: ['TypeScript', 'Node.js', 'Kubernetes', 'PostgreSQL'],
    salaryRange: { min: 30000, max: 38000, currency: 'PLN' },
    slug: 'demo-lead-architect',
    description: 'Drive platform architecture across distributed systems and cloud services.',
  },
  {
    id: '5',
    titleTemplate: () => 'Junior Backend Developer',
    company: 'InnoWorks',
    city: 'Gdansk / Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'junior',
    requiredSkills: ['Node.js', 'TypeScript', 'PostgreSQL', 'Git'],
    salaryRange: { min: 9000, max: 12000, currency: 'PLN' },
    slug: 'demo-junior-backend',
    description: 'Build backend APIs with senior developer mentoring.',
  },
  {
    id: '6',
    titleTemplate: () => 'Full Stack Engineer',
    company: 'SaaSify Global',
    city: 'Wroclaw / Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'mid',
    requiredSkills: ['TypeScript', 'React', 'Next.js', 'GraphQL'],
    salaryRange: { min: 17000, max: 23000, currency: 'PLN' },
    slug: 'demo-fullstack-saasify',
    description: 'Scale our multi-tenant B2B SaaS platform.',
  },
  {
    id: '7',
    titleTemplate: () => 'Senior Frontend Developer',
    company: 'StreamLine Media',
    city: 'Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'senior',
    requiredSkills: ['React', 'Next.js', 'TypeScript', 'Tailwind'],
    salaryRange: { min: 22000, max: 28000, currency: 'PLN' },
    slug: 'demo-senior-streamline',
    description: 'Deliver high-throughput streaming web applications.',
  },
  {
    id: '8',
    titleTemplate: () => 'DevOps / Cloud Engineer',
    company: 'Kubiq Systems',
    city: 'Warsaw',
    isRemote: false,
    workplaceType: 'office',
    seniority: 'senior',
    requiredSkills: ['AWS', 'Docker', 'Kubernetes', 'Terraform'],
    salaryRange: { min: 24000, max: 30000, currency: 'PLN' },
    slug: 'demo-devops-kubiq',
    description: 'Automate CI/CD pipelines and infrastructure as code.',
  },
  {
    id: '9',
    titleTemplate: () => 'React Native Specialist',
    company: 'MobileCraft',
    city: 'Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'mid',
    requiredSkills: ['React', 'React Native', 'TypeScript', 'iOS'],
    salaryRange: { min: 18000, max: 24000, currency: 'PLN' },
    slug: 'demo-mobilecraft',
    description: 'Build cross-platform mobile apps for millions of users.',
  },
  {
    id: '10',
    titleTemplate: () => 'AI Full Stack Developer',
    company: 'NeuralFlow',
    city: 'Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'senior',
    requiredSkills: ['Python', 'TypeScript', 'React', 'Next.js'],
    salaryRange: { min: 25000, max: 32000, currency: 'PLN' },
    slug: 'demo-neuralflow-ai',
    description: 'Integrate LLMs and generative agents into enterprise workflows.',
  },
  {
    id: '11',
    titleTemplate: () => 'Platform Engineer',
    company: 'CoreData Tech',
    city: 'Krakow / Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'mid',
    requiredSkills: ['Go', 'TypeScript', 'PostgreSQL', 'Docker'],
    salaryRange: { min: 19000, max: 25000, currency: 'PLN' },
    slug: 'demo-coredata-platform',
    description: 'Develop data ingestion pipelines and microservices.',
  },
  {
    id: '12',
    titleTemplate: () => 'Junior Frontend Developer',
    company: 'BrightPixel',
    city: 'Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'junior',
    requiredSkills: ['JavaScript', 'HTML', 'CSS', 'React'],
    salaryRange: { min: 8000, max: 11000, currency: 'PLN' },
    slug: 'demo-brightpixel-junior',
    description: 'Learn and create accessible, modern web interfaces.',
  },
  {
    id: '13',
    titleTemplate: () => 'Staff Backend Architect',
    company: 'VaultPay',
    city: 'Warsaw / Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'lead',
    requiredSkills: ['Node.js', 'TypeScript', 'PostgreSQL', 'Redis'],
    salaryRange: { min: 32000, max: 40000, currency: 'PLN' },
    slug: 'demo-vaultpay-staff',
    description: 'Lead core payments engine architecture and reliability.',
  },
  {
    id: '14',
    titleTemplate: () => 'UI/UX Web Engineer',
    company: 'DesignSystem Inc',
    city: 'Poznan / Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'mid',
    requiredSkills: ['TypeScript', 'React', 'Tailwind', 'Storybook'],
    salaryRange: { min: 16000, max: 21000, currency: 'PLN' },
    slug: 'demo-designsystem-ui',
    description: 'Build and maintain our global design system component library.',
  },
  {
    id: '15',
    titleTemplate: () => 'Senior Node.js Developer',
    company: 'APIWorks',
    city: 'Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'senior',
    requiredSkills: ['Node.js', 'TypeScript', 'PostgreSQL', 'Docker'],
    salaryRange: { min: 21000, max: 27000, currency: 'PLN' },
    slug: 'demo-apiworks-senior',
    description: 'Build robust REST and GraphQL APIs handling millions of requests.',
  },
  {
    id: '16',
    titleTemplate: () => 'Full Stack Product Developer',
    company: 'EarlyStage Lab',
    city: 'Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'mid',
    requiredSkills: ['TypeScript', 'React', 'Next.js', 'Supabase'],
    salaryRange: { min: 17000, max: 22000, currency: 'PLN' },
    slug: 'demo-earlystage-fullstack',
    description: 'Rapidly prototype and iterate on user-facing product features.',
  },
  {
    id: '17',
    titleTemplate: () => 'Cloud Infrastructure Architect',
    company: 'SkyScale Net',
    city: 'Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'senior',
    requiredSkills: ['AWS', 'Kubernetes', 'Terraform', 'TypeScript'],
    salaryRange: { min: 26000, max: 33000, currency: 'PLN' },
    slug: 'demo-skyscale-cloud',
    description: 'Architect resilient multi-region cloud infrastructures.',
  },
  {
    id: '18',
    titleTemplate: () => 'Senior Web Performance Engineer',
    company: 'FastTrack Web',
    city: 'Remote',
    isRemote: true,
    workplaceType: 'remote',
    seniority: 'senior',
    requiredSkills: ['TypeScript', 'JavaScript', 'React', 'Next.js'],
    salaryRange: { min: 23000, max: 29000, currency: 'PLN' },
    slug: 'demo-fasttrack-perf',
    description: 'Optimize web core vitals and frontend bundle efficiency.',
  },
];
